# Generated by Django 4.1.7 on 2023-05-06 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_auto_20220526_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 18, 52, 58, 804494)),
        ),
    ]
