# Generated by Django 4.1.6 on 2023-05-07 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0014_alter_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='with_qr',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 20, 28, 43, 208991)),
        ),
    ]
