# Generated by Django 4.1.6 on 2023-05-07 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 21, 21, 7, 434583)),
        ),
    ]
